{
  "Header": {
    "Original": "CVE-2020-8631 (cloud-init through 19.4 relies on Mersenne Twister for a random passwo ...)",
    "Line": 109798,
    "ID": "CVE-2020-8631",
    "Description": "(cloud-init through 19.4 relies on Mersenne Twister for a random passwo ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2113-1}",
      "Line": 109799,
      "Type": "xref",
      "Bugs": [
        "DLA-2113-1"
      ]
    },
    {
      "Original": "- cloud-init 19.4-2 (bug #951362)",
      "Line": 109800,
      "Type": "package",
      "Package": "cloud-init",
      "Kind": "fixed",
      "Version": "19.4-2",
      "BugNo": 951362
    },
    {
      "Original": "[bullseye] - cloud-init \u003cno-dsa\u003e (Minor issue)",
      "Line": 109801,
      "Type": "package",
      "Release": "bullseye",
      "Package": "cloud-init",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[stretch] - cloud-init \u003cno-dsa\u003e (Minor issue)",
      "Line": 109802,
      "Type": "package",
      "Release": "stretch",
      "Package": "cloud-init",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1860795",
      "Line": 109803,
      "Type": "NOTE",
      "Description": "https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1860795"
    },
    {
      "Original": "NOTE: https://github.com/canonical/cloud-init/pull/204",
      "Line": 109804,
      "Type": "NOTE",
      "Description": "https://github.com/canonical/cloud-init/pull/204"
    }
  ]
}